packageExtensions:
  "@cucumber/cucumber@*":
    dependencies:
      "ts-node": "*"   
      "@cucumber/pretty-formatter": "*"   
  "vite-express@*":
    dependencies:
      "express": "*"
      "vite": "*"
      
yarnPath: .yarn/releases/yarn-4.0.2.cjs
